### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by karolmie1** [nicusX/spring-hateoas-sample#1]
Hey! After clicking into http://localhost:8080/authors, or any link like this this error pops out:

<div>
Could not marshal [Resources { content: [links: [<http://localhost:8080/books/0596007736>;rel="self", <http://localhost:8080/books/0596007736/purchase>;rel="purchase", <http://localhost:8080/books/0596007736/borrow-a-copy>;rel="borrow", <http://localhost:8080/books/0596007736/return-a-copy>;rel="return", <http://localhost:8080/authors/david_flanagan>;rel="authors", <http://localhost:8080/publishers/1>;rel="publisher"], links: [<http://localhost:8080/books/0321127420>;rel="self", <http://localhost:8080/books/0321127420/purchase>;rel="purchase", <http://localhost:8080/books/0321127420/borrow-a-copy>;rel="borrow", <http://localhost:8080/books/0321127420/return-a-copy>;rel="return", <http://localhost:8080/authors/martin_fowler>;rel="authors", <http://localhost:8080/authors/kendall_scott>;rel="authors", <http://localhost:8080/publishers/2>;rel="publisher"], links: [<http://localhost:8080/books/0321193687>;rel="self", <http://localhost:8080/books/0321193687/purchase>;rel="purchase", <http://localhost:8080/books/0321193687/return-a-copy>;rel="return", <http://localhost:8080/authors/martin_fowler>;rel="authors", <http://localhost:8080/publishers/2>;rel="publisher"]], links: [<http://localhost:8080/books>;rel="self"] }]: null; nested exception is javax.xml.bind.MarshalException - with linked exception: [com.sun.istack.internal.SAXException2: unable to marshal type "com.opencredo.demo.hateoas.api.resources.BookResource" as an element because it is missing an @XmlRootElement annotation]
</div>

**Comment by nicusX** [comment]
Maybe you posted some invalid data. 
This sample application does no validation check, for simplicity.

**Comment by karolmie1** [comment]
The error came up while using sample data from master:
mvn spring-boot:run -Dspring.profiles.active=sampledata

I didn't investigate further, but i thought i should give you some feedback.
The error was ofc internal server error.

**Comment by nicusX** [comment]
Thank you for the feedback.
The point is, it works for me (checked right now):
1. `mvn spring-boot:run -Dspring.profiles.active=sampledata`
2. `curl http://localhost:8080/authors` (or any other url from the links returned by the API) generate a correct JSON response.

You said "clicking" the link. Do you mean you are using the browser to navigate the API? Try with a tool like curl or a GUI tool like Postman. Maybe the browser is adding something unexpected to the request (I'm guessing)
